type: "paradit"
gpu: "2"
model_path: "/home/wentao/xzw/LLM/gpt-j-6b" # gpt-j-6b phi-2  /home/wentao/xzw/LLM/phi-2
model_state_dir: "/home/wentao/xzw/checkpoint/204_20250307074919/checkpoints/model_epoch_all_50000.pth"
data_type: "cf"
data_range: 1024 # 1022 1005
fi: 1024 # 1024
layer: 9 # 29
noisetype: -1
ps: 100
is_fc2bias: true   # true false
hidden: 768
nheads: 12
gtype: "bert2para" # hidden2para  bert2para
batch_size: 512
temp: "cf"
# /home/wentao/xzw/LLM/bert_gptj_cf_checkpoints_infoNCE/model_epoch_9600.pth None
# /home/wentao/xzw/LLM/bert_gptj_cf_checkpoints_2000/model_epoch_20000.pth
bmodel_train_state_path: "None"
result_path: "result_evaluation/"
model_para_type: "gptj" # phi2 gptj
para_dir: '/home/wentao/xzw/data_paras_v2/cf_gptj/cf_layer_9/all'
data_dir: '/home/wentao/xzw/data_paras_v2/loc/cf_gptj_loc_10000.json'
is_normal: true
is_rel: false