type: "paradit"
gpu: "3"
model_path: "microsoft/phi-2"
model_state_dir: "results/029_20250518224950/checkpoints/model_epoch_all_30000.pth"
data_type: "zsre"
data_range: 10 # 1022 1005
fi: 10 # 1024
layer: 29 # 29
noisetype: 0
ps: 100
is_fc2bias: true   # true false
hidden: 768
nheads: 12
gtype: "bert2para" # hidden2para  bert2para
batch_size: 1000
temp: newzsre
bmodel_train_state_path: "checkpoints_trained_bert/bert_phi2_zsre/model_epoch_100.pth"
result_path: "result_evaluation/"
model_para_type: "phi2"
para_dir: 'data_paras/phi2_zsre_10000/paras'
data_dir: 'data/edit_data/phi2_zsre_edit.json'
is_normal: true
is_rel: true