type: "paradit"
gpu: "4"
model_path: "/home/wentao/xzw/LLM/gpt-j-6b" # gpt-j-6b phi-2  /home/wentao/xzw/LLM/phi-2
model_state_dir: "/home/wentao/xzw/checkpoint/063_20250312235842/checkpoints/model_epoch_all_312000_sum0.4159_v1.pth"
data_type: "zsre"
data_range: 10 # 1022 1005
fi: 10 # 1024
layer: 9 # 29
noisetype: 0
ps: 100
is_fc2bias: true   # true false
hidden: 768
nheads: 12
gtype: "bert2para" # hidden2para  bert2para
batch_size: 1000
temp: newzsre # zsre
bmodel_train_state_path: "/home/wentao/xzw/LLM/bert_gptj_zsre_checkpoints_infoNCE_case2/model_epoch_100.pth"
result_path: "result_evaluation/"
model_para_type: "gptj" # phi2 gptj
para_dir: '/home/wentao/xzw/data_paras_v2/zsre_gptj/zsre_layer_9/all'
data_dir: '/home/wentao/xzw/data_paras_v2/loc/zsre_gptj_edit.json'
is_normal: true
is_rel: true