type: "paradit"
gpu: "4"
model_path: "microsoft/phi-2"
model_state_dir: "results/204_20250307074919/checkpoints/model_epoch_all_30000.pth"
data_type: "cf"
data_range: 1024 # 1022 1005
fi: 1024 # 1024
layer: 29 # 29
noisetype: 0
ps: 100
is_fc2bias: true   # true false
hidden: 768
nheads: 12
gtype: "bert2para" # hidden2para  bert2para
batch_size: 512
bmodel_train_state_path: "checkpoints_trained_bert/bert_phi2_cf/model_epoch_5100.pth"
result_path: "result_evaluation/"
model_para_type: "phi2" # phi2 gptj
para_dir: "data_paras/phi2_cf_10000/paras"
data_dir: 'data/edit_data/phi2_cf_edit.json'
is_normal: true
is_rel: true