# Fixed config
global_seed: 0
ps: 100
nheads: 12
nblocks: 24
hidden: 768
epochs: 1000000
lr: 0.0001
noisepara_dir: /home/wentao/xzw/data_paras/my_noise_paras
is_bert_norm: true

# Dynamic config
bertft_dir: /home/wentao/xzw/LLM/bert_gptj_cf_checkpoints_infoNCE/model_epoch_9600.pth
paras_dir: /home/wentao/xzw/data_paras/cf_gptj/cf_layer_9/all
rephrases_dir: /home/wentao/xzw/data_paras/cf_gptj/cf_layer_9/train_success_data_gptj_prompt_3_6_neuron_1_layer_9.json
layer: 9
seq_len: 8193
isbert_0or1: 1

# Noise config
is_noise: true
noisetype: 0
noise_n1024: 0.1
noisetype_10or2: 1

# Hyperparameter config
model_para_type: gptj
data_type: cf
fi: 10000 # 1024 or 10000
## if ddp
gpus: 0,1,2,3,4
global_batch_size: 1000 # batch * gpus
