# Fixed config
global_seed: 0
ps: 100
nheads: 12
nblocks: 12
hidden: 768
epochs: 1000000
lr: 0.0001
is_bert_norm: true

# Dynamic config
bertft_dir: checkpoints_trained_bert/bert_gptj_cf/model_epoch_9600.pth
paras_dir: data_paras/gptj_cf_10000/paras
rephrases_dir: data_paras/gptj_cf_10000/train_success_data_prompt_3_6_neuron_1_layer_9.json
layer: 9
seq_len: 8193
isbert_0or1: 1

# Noise config
is_noise: false
noisetype: 0
noise_n1024: 1.0
noisetype_10or2: 1
noisephrases_dir: data/new_split_data/multi_counterfact_new_id.json

# Hyperparameter config
model_para_type: gptj
data_type: cf
gpu: '1'
batch: 255
fi: 4096
